### ISSUE TITLE
Will the sandbox API key work with this, or only the regular API access key?

### ISSUE THREAD

**Issue by matttMP** [wallopthecat/namecheap-domain-sniper#3]
Hello, 

I am planning on sniping a domain that will expire in a few months, and I found this tool. However, in order to get a Namecheap API key, you need to meet the following requirements, only to qualify: 

`"To qualify, you must have: Account balance of $50+, 20+ domains in your account, or purchases totaling $50+ within the last 2 years."`

These requirements are outrageous to me, and I cannot meet them just for one domain.

I read up on the "Intro to API" article in Namecheap's support section, and I saw there is an option for a "Sandbox Environment API Key", but I am unsure if this type of API key will work with this tool. Please let me know, because the time for this domain is running out! 

Thank you.

**Comment by wallopthecat** [comment]
I don't think a sandbox key will work and I agree that the restrictions they have are silly. Best of luck
